markdown:  kramdown
title: Bob van Luijt
exclude: 
    - data
    - getStats/*
    - html/*
    - loadOldData.sh
    - renderStats.py
    - CNAME
    - getStats.zip
    - getStats.zip.enc
    - requirements.txt